Add git PPA only when required

diff --git a/.github/workflows/reusable.yml b/.github/workflows/reusable.yml
--- a/.github/workflows/reusable.yml
+++ b/.github/workflows/reusable.yml
@@ -298,13 +298,22 @@ jobs:
             if [ -n "${{matrix.container}}" ] && [ -f "/etc/debian_version" ]; then
                 apt-get -o Acquire::Retries=$NET_RETRY_COUNT update
                 apt-get -o Acquire::Retries=$NET_RETRY_COUNT -y -q --no-install-suggests --no-install-recommends install sudo software-properties-common curl
-                # Need (newer) git, and the older Ubuntu container may require requesting the key manually using port 80
-                key_server="keyserver.boost.org"
-                echo "Downloading key from $key_server"
-                curl -sSL --retry ${NET_RETRY_COUNT:-5} "https://$key_server/pks/lookup?op=get&search=0xE1DD270288B4E6030699E45FA1715D88E1DF1F24" | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/git-core_ubuntu_ppa.gpg
-                for ((i=1; i <= ${NET_RETRY_COUNT:-3}; i++)); do
-                    sudo -E add-apt-repository -y ppa:git-core/ppa && break || sleep 10
-                done
+                if ! git_version=$(git --version 2>/dev/null); then
+                    git_version=0.0.0
+                fi
+                # Extract version number from e.g. "git version 2.7.4"
+                version=${git_version##* }
+                echo "Git version: $version"
+                required_git_version="2.9"
+                if [[ ${GIT_FETCH_JOBS:-1} != "1" ]] && [[ "$(printf '%s\n' "$required" "$version" | sort -V | head -n1)" != "$required" ]]; then
+                    # Need (newer) git, and the older Ubuntu container may require requesting the key manually using port 80
+                    key_server="keyserver.boost.org"
+                    echo "Downloading key from $key_server"
+                    curl -sSL --retry ${NET_RETRY_COUNT:-5} "https://$key_server/pks/lookup?op=get&search=0xE1DD270288B4E6030699E45FA1715D88E1DF1F24" | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/git-core_ubuntu_ppa.gpg
+                    for ((i=1; i <= ${NET_RETRY_COUNT:-3}; i++)); do
+                        sudo -E add-apt-repository -y ppa:git-core/ppa && break || sleep 10
+                    done
+                fi
                 apt-get -o Acquire::Retries=$NET_RETRY_COUNT update
                 osver=$(lsb_release -sr | cut -f1 -d.)
                 pkgs="g++ git xz-utils"
